name: National Security
favicon: null
layout_spectrum: 0.2976145315915346
typography_spectrum: 0.35357119562104344
title: National Security Thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#771622'
    - '#15232a'
    - '#030303'
    - '#d2c69e'
    - '#695940'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
